### ISSUE TITLE
How to display string content?

### ISSUE THREAD

**Issue by mrhanCH** [danielmader/MatrixClock_MicroPythonESP#1]
Hello, great job. I noticed in your presentation that the red time doesn't seem very clear. Is it due to insufficient brightness? Or is it due to camera shooting?
Also, may I ask if you have a suitable method for displaying English words or Chinese characters?
Thank you!

**Comment by danielmader** [comment]
Thanks for your comment! 
There is no way to write letters directly with the low level approach of my project. 
Maybe the Hub75 library of Circuit Python can help you. 
Best luck!
